### ISSUE TITLE
Change to cmake

### ISSUE THREAD

**Issue by KaoCC** [KaoCC/HeterogeneousQueue#18]
Change to cmake

**Comment by MedicineYeh** [comment]
Basic Tutorial:
https://zh.wikibooks.org/zh-tw/CMake_%E5%85%A5%E9%96%80/%E7%B0%A1%E5%96%AE%E7%9A%84%E7%AF%84%E4%BE%8B

A bit more tutorial:
https://zh.wikibooks.org/zh-tw/CMake_%E5%85%A5%E9%96%80/%E5%BB%BA%E7%BD%AE%E8%88%87%E9%80%A3%E7%B5%90%E7%A8%8B%E5%BC%8F%E5%BA%AB

Generate libs in a different folder:
https://stackoverflow.com/questions/6293769/moving-headers-libraries-executables-to-specific-directories?rq=1

Build Types:
https://zh.wikibooks.org/zh-tw/CMake_%E5%85%A5%E9%96%80/%E5%8A%A0%E5%85%A5%E7%B7%A8%E8%AD%AF%E9%81%B8%E9%A0%85

Testing System:
https://cmake.org/Wiki/CMake/Testing_With_CTest

**Comment by MedicineYeh** [comment]
PR #19

**Comment by MedicineYeh** [comment]
I just found out that GLOB generates the file list at the execution of cmake instead of make, thus I changed the following codes for you. This does the same thing but will find the files when running `make install`. You can do this patch to all your CMake files.

BTW, you might want to fix the path of installed header files since they somehow reference to each other without a subfolder name. (This relies on user adding `-I/PTAH/` to compiler flags when compiling their OpenCL codes. )

``` diff
-# Get files that should be installed to target prefix
-FILE(GLOB PUBLIC_HEADER_FILES ${PROJECT_SOURCE_DIR}/include/*)
-
-install(FILES ${PUBLIC_HEADER_FILES}
-    DESTINATION include/${PROJECT_NAME}
-    )
+#install(DIRECTORY include/
+#    DESTINATION include/${PROJECT_NAME}
+#    FILES_MATCHING PATTERN "*.h*"
+#    )
```

**Comment by KaoCC** [comment]
updated
